@baseURL= http://localhost:8000
@categories = http://localhost:8000/categories
@questions = http://localhost:8000/questions
@answers = http://localhost:8000/answers

##############################################################
########################## TEST ##############################
##############################################################

GET {{baseURL}}/ping

##############################################################
######################## CATEGORY ############################
##############################################################

### GET ALL
GET {{categories}}

### GET BY ID
GET {{categories}}/1

### SEARCH
GET {{categories}}/search?partial_name=lin

### CREATE 1
POST {{categories}}
Content-Type: application/json

{
    "name": "Git",
    "description": "Version control for developing"
}

### CREATE 2
POST {{categories}}
Content-Type: application/json

{
    "name": "Linux",
    "description": "Operating System"
}

### UPDATE
PATCH {{categories}}/2
Content-Type: application/json

{
    "description": "Best operating system"
}

### DELETE
DELETE {{categories}}/2

##############################################################
######################## QUESTION ############################
##############################################################

### GET ALL
GET {{questions}}

### GET BY ID
GET {{questions}}/2

### SEARCH
GET {{questions}}/search?partial_title=created

### CREATE 1
POST {{questions}}
Content-Type: application/json

{
    "title": "Who created Git?",
    "difficulty": "easy",
    "explanation": "Linus Torvalds created Git in 2005",
    "category_id": 1
}

### CREATE 2
POST {{questions}}
Content-Type: application/json

{
    "title": "Who created Linux kernel?",
    "difficulty": "easy",
    "explanation": "Linus Torvalds created Git in 1991",
    "category_id": 2
}

### CREATE 3
POST {{questions}}
Content-Type: application/json

{
    "title": "What does the git status command does?",
    "difficulty": "easy",
    "explanation": "This command gives information of the status of the current branch",
    "category_id": 1
}

### UPDATE
PATCH {{questions}}/2
Content-Type: application/json

{
    "explanation": "Linus Torvalds created Linux in 1991"
}

### DELETE
DELETE {{questions}}/3

##############################################################
######################### ANSWER #############################
##############################################################

### GET ALL
GET {{answers}}

### GET BY ID
GET {{answers}}/2

### SEARCH
GET {{answers}}/search?partial_title=created

### CREATE 1.1
POST {{answers}}
Content-Type: application/json

{
    "title": "Who created Git?",
    "difficulty": "easy",
    "explanation": "Linus Torvalds created Git in 2005",
    "category_id": 1
}

### CREATE 1.2


### CREATE 1.3


### CREATE 1.4


### UPDATE
PATCH {{answers}}/2
Content-Type: application/json

{
    "explanation": "Linus Torvalds created Linux in 1991"
}

### DELETE
DELETE {{answers}}/3